#!/usr/bin/env bash
# Regenerate .env from the running local Supabase stack. .env is fully derived —
# put any hand-maintained values in .env.local instead (Expo loads both).
#
#   LAN_IP=192.168.0.68 bash scripts/write-env.sh   # override the detected LAN IP
set -euo pipefail
cd "$(dirname "$0")/.."

status="$(npx supabase status -o env 2>/dev/null)" || {
  echo "Supabase is not running — run: npm run setup" >&2
  exit 1
}
value() { printf '%s\n' "$status" | sed -n "s/^$1=\"\{0,1\}\([^\"]*\)\"\{0,1\}$/\1/p"; }

api_url="$(value API_URL)"
publishable="$(value PUBLISHABLE_KEY)"
secret="$(value SECRET_KEY)"
db_url="$(value DB_URL)"
[ -n "$api_url" ] && [ -n "$publishable" ] && [ -n "$secret" ] || {
  echo "Could not read keys from 'supabase status'" >&2
  exit 1
}

# A physical phone needs the Mac's LAN IP; 127.0.0.1 would point at the phone itself.
lan_ip="${LAN_IP:-}"
if [ -z "$lan_ip" ] && command -v ipconfig >/dev/null 2>&1; then
  lan_ip="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)"
fi
port="${api_url##*:}"
app_url="http://${lan_ip:-127.0.0.1}:${port}"

cat > .env <<EOF
# GENERATED by scripts/write-env.sh — do not edit; regenerated by npm run setup.
# Hand-maintained values go in .env.local.
EXPO_PUBLIC_SUPABASE_URL=$app_url
EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY=$publishable
SUPABASE_SECRET_KEY=$secret
SUPABASE_DB_URL=$db_url
EOF

echo "Wrote .env (app URL: $app_url)"
[ -n "$lan_ip" ] || echo "Note: no LAN IP detected — a physical phone won't reach the stack. Re-run with LAN_IP=<ip>."
